# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Reference name for this presentation. Only visible in the admin.', max_length=255, verbose_name='nom')),
                ('transitionTime', models.PositiveIntegerField(help_text='Number of seconds to display each slide.', verbose_name='transition time')),
                ('pauseTimeOnTouch', models.PositiveIntegerField(help_text='If someone interacts with the kiosk, stop the slideshow for this number of seconds.', verbose_name='pause time on touch')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('', ''), ('image', 'Image'), ('event', 'Event'), ('eventList', 'Event list')], default=None, max_length=32, verbose_name='type')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slides/%Y/%m/%d/', verbose_name='image')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='events.Event')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='presentations.Presentation')),
            ],
        ),
    ]
