# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ('position',)},
        ),
        migrations.AddField(
            model_name='slide',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='name',
            field=models.CharField(help_text="Nom de référence de cette présentation. Seulement visible dans la console d'administration.", max_length=255, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='pauseTimeOnTouch',
            field=models.PositiveIntegerField(help_text="Suspendre le diaporama pour ce nombre de secondes lors d'une interaction avec le kiosque.", verbose_name="temps de pause lors d'une interaction"),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='transitionTime',
            field=models.PositiveIntegerField(help_text="Nombre de secondes d'affichage de chaque diapositive.", verbose_name='temps de transition'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='type',
            field=models.CharField(choices=[('', ''), ('image', 'Image'), ('event', 'Événement'), ('eventList', "Liste d'événements")], default=None, max_length=32, verbose_name='type'),
        ),
    ]
