# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-16 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0002_auto_20160125_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='displayIndicators',
            field=models.BooleanField(default=True, help_text='Whether or not to display the little dots at the bottom that show slideshow progress.', verbose_name='display indicators'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='displayMenu',
            field=models.BooleanField(default=True, help_text='Whether or not the menu should appear on this presentation.', verbose_name='display menu'),
        ),
    ]
