# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0002_auto_20160118_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='events.Event'),
        ),
    ]
