# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-21 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0003_auto_20160516_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='location',
            field=models.CharField(blank=True, help_text='A comma-delimited country name and country code (ISO 3166)', max_length=255, null=True, verbose_name='emplacement'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='type',
            field=models.CharField(choices=[('', ''), ('image', 'Image'), ('event', 'Événement'), ('eventList', "Liste d'événements"), ('weather', 'Weather')], default=None, max_length=32, verbose_name='type'),
        ),
    ]
