# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0003_auto_20160118_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='type',
            field=models.CharField(choices=[('', ''), ('image', 'Image'), ('event', 'Event'), ('eventList', 'Event list')], default=None, max_length=32, verbose_name='type'),
        ),
    ]
