# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0006_auto_20160622_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='headerImage',
            field=models.ImageField(blank=True, null=True, upload_to='headers/', verbose_name='header image'),
        ),
        migrations.AddField(
            model_name='slide',
            name='displayType',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('DAILY', 'Daily')], default='MONTHLY', max_length=32, verbose_name='event list display type'),
        ),
    ]
