# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import event_kiosk.content.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Page title. Will be shown in menu and top application bar.', max_length=60, verbose_name='title')),
                ('icon', models.FileField(blank=True, null=True, upload_to='icons/%Y/%m/%d/', validators=[event_kiosk.content.models.validate_svg_files], verbose_name='icon (svg)')),
                ('html', models.TextField(verbose_name='content (html)')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name for this section. Will be shown in menu.', max_length=60, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='WebAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.FileField(help_text='Add any asset you wish to save on the server to be used on the page, like images, css, js, etc...', upload_to='', verbose_name='file')),
                ('page', models.ForeignKey(help_text='Page on which this asset is used.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='content.Page')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='content.Section'),
        ),
    ]
