# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiosks', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='kiosk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='kiosks.Kiosk'),
        ),
        migrations.AlterField(
            model_name='webasset',
            name='asset',
            field=models.FileField(help_text='Add any asset you wish to save on the server to be used on the page, like images, css, js, etc...', upload_to='assets/%Y/%m/%d/', verbose_name='file'),
        ),
    ]
