# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20160120_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['weight']},
        ),
        migrations.AddField(
            model_name='page',
            name='weight',
            field=models.IntegerField(default=0, help_text='Pages in the menu will be ordered by weight', verbose_name='weight'),
        ),
    ]
