# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-16 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0003_auto_20160516_1156'),
        ('kiosks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskPresentationCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField(verbose_name='datetime')),
                ('endTime', models.DateTimeField(verbose_name='datetime')),
                ('kiosk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosks.Kiosk')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presentations.Presentation')),
            ],
        ),
        migrations.AddField(
            model_name='kiosk',
            name='presentation_calendar',
            field=models.ManyToManyField(through='kiosks.KioskPresentationCalendar', to='presentations.Presentation'),
        ),
    ]
