# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0004_auto_20160118_1452'),
        ('kiosks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiosk',
            name='presentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='presentations.Presentation'),
        ),
    ]
