# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('date', models.DateField(verbose_name='date')),
                ('startTime', models.TimeField(verbose_name='start time')),
                ('endTime', models.TimeField(verbose_name='end time')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(upload_to='events/%Y/%m/%d/', verbose_name='image')),
                ('location', models.CharField(max_length=100, verbose_name='location')),
            ],
        ),
    ]
