# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('image', models.ImageField(null=True, upload_to='speakers/%Y/%m/%d/', verbose_name='image')),
                ('bio', models.TextField(verbose_name='bio')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(to='events.Speaker'),
        ),
    ]
