# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20160120_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='shortTitle',
            field=models.CharField(blank=True, help_text='you can provide a shorter title for the event list.', max_length=50, null=True, verbose_name='short title'),
        ),
        migrations.AddField(
            model_name='event',
            name='subTitle',
            field=models.CharField(blank=True, help_text='optional subtitle for the event list.', max_length=50, null=True, verbose_name='subtitle'),
        ),
        migrations.AlterField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(blank=True, to='events.Speaker'),
        ),
    ]
