# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20160121_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('date', 'startTime')},
        ),
        migrations.AlterField(
            model_name='event',
            name='endTime',
            field=models.TimeField(verbose_name='heure de fin'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=100, verbose_name='emplacement'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registrationUrl',
            field=models.URLField(blank=True, help_text='URL pour les inscriptions à cet événement. Sera encodé dans le code QR.', null=True, verbose_name="url d'inscription"),
        ),
        migrations.AlterField(
            model_name='event',
            name='shortTitle',
            field=models.CharField(blank=True, help_text='Vous pouvez fournir un titre plus court pour la liste des événements.', max_length=50, null=True, verbose_name='titre court'),
        ),
        migrations.AlterField(
            model_name='event',
            name='startTime',
            field=models.TimeField(verbose_name='heure de début'),
        ),
        migrations.AlterField(
            model_name='event',
            name='subTitle',
            field=models.CharField(blank=True, help_text='sous-titre optionnel pour la liste des événements.', max_length=50, null=True, verbose_name='sous-titre'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255, verbose_name='titre'),
        ),
    ]
