# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 10:01
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20160125_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='prettyUrl',
            field=models.URLField(blank=True, help_text='Human friendly url to overlay with event image', null=True, verbose_name='pretty url'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='description'),
        ),
    ]
