# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20160202_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='prettyUrl',
            field=models.CharField(blank=True, help_text="URL lisible par les humains pour superposer avec l'image de l'événement.", max_length=150, null=True, verbose_name='url propre'),
        ),
    ]
